[package]
name = "hnefatafl"
version = "0.1.0"
authors = ["LFalch <lucas@wasd.dk>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
rocket_contrib = {version = "0.4.5", features = ["tera_templates"]}
serde = "1"
serde_derive = "1"
rand = "0.7"
websocket = "0.24"
